public enum UIPopupType
{
    UICharacterPopup,
    UILoadRestaurantPopup,
    UIMenuPopup,
    UIFoodDetailPopup,
    UIGameConfirmPopup,
    UIGameNotiPopup,
    UIInputNamePopup,
    UIInventoryPopup,
    UILevelUpPopup,
    UILoadingPopup,
    UILoginPopup,
    UIMainMenuPopup,
    UINewRestaurantPopup,
    UIOptionMenuPopup,
    UIRestaurantPopup,
    UIRewardPopup,
    UISettingPopup,
    UIShopPopup,
    UIUpgradePopup
}
